// frontend/controla-tus-gastos-angular/src/app/feature/home/home.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router } from '@angular/router';

//material
import { MatButtonModule } from '@angular/material/button';
import { MatToolbarModule } from '@angular/material/toolbar';
import { MatIconModule } from "@angular/material/icon";

@Component({
  selector: 'app-home',
  standalone: true,
  imports: [CommonModule, MatButtonModule, MatToolbarModule, MatIconModule],
  templateUrl: './home.component.html',
  styleUrl: './home.component.css'
})
export class HomeComponent {
  constructor(private router: Router) { }

  redirectToLogin() {
    this.router.navigate(['/login']);
  }

}

<mat-toolbar color="primary">
  <span>Controla tus gastos</span>
  <span class="spacer"></span>
  <button mat-raised-button (click)="redirectToLogin()">
    <mat-icon>person</mat-icon> Ingresar
  </button>
</mat-toolbar>

// frontend/controla-tus-gastos-react/src/feature/home/Home.tsx
import "./home.css";

//mui
import Button from "@mui/material/Button";
import PersonIcon from "@mui/icons-material/Person";
import AppBar from "@mui/material/AppBar";
import Box from "@mui/material/Box";
import Toolbar from "@mui/material/Toolbar";
import Typography from "@mui/material/Typography";

//router
import { Link } from "react-router-dom";

const Home: React.FC = () => {
    return (
        <Box sx={{ flexGrow: 1 }}>
            <AppBar position="static">
                <Toolbar>
                    <Typography
                        variant="h6"
                        component="div"
                        sx={{ flexGrow: 1 }}
                    >
                        Controla tus gastos
                    </Typography>
                    <Link to={"/login"}>
                        <Button
                            variant="outlined"
                            startIcon={<PersonIcon color="primary" />}
                            style={{ backgroundColor: "#fff" }}
                        >
                            Ingresar
                        </Button>
                    </Link>
                </Toolbar>
            </AppBar>
        </Box>
    );
};

export default Home;
